///* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

//   Licensed under the MIT license.

//   Copyright 2016 Xamarin Inc

//   This notice may not be removed from any source distribution.
//   See LICENSE file for licensing details.
//*/

//using System;

//namespace Vulkan {
//    internal partial struct VkWin32SurfaceCreateInfoKhr {
//        internal VkStructureType SType;
//        internal IntPtr Next;
//        internal UInt32 Flags;
//        internal IntPtr Hinstance;
//        internal IntPtr Hwnd;
//    }

//    internal partial struct VkImportMemoryWin32HandleInfoNv {
//        internal VkStructureType SType;
//        internal IntPtr Next;
//        internal VkExternalMemoryHandleTypeFlagsNv HandleType;
//        internal IntPtr Handle;
//    }

//    internal partial struct VkExportMemoryWin32HandleInfoNv {
//        internal VkStructureType SType;
//        internal IntPtr Next;
//        internal IntPtr Attributes;
//        internal UInt32 DwAccess;
//    }

//    internal partial struct VkWin32KeyedMutexAcquireReleaseInfoNv {
//        internal VkStructureType SType;
//        internal IntPtr Next;
//        internal UInt32 AcquireCount;
//        internal IntPtr AcquireSyncs;
//        internal IntPtr AcquireKeys;
//        internal IntPtr AcquireTimeoutMilliseconds;
//        internal UInt32 ReleaseCount;
//        internal IntPtr ReleaseSyncs;
//        internal IntPtr ReleaseKeys;
//    }

//}
