/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;

namespace Vulkan {
    public enum VkAttachmentLoadOp : int {
        AttachmentLoadOpLoad = 0,
        AttachmentLoadOpClear = 1,
        AttachmentLoadOpDontCare = 2,
    }

    public enum VkAttachmentStoreOp : int {
        AttachmentStoreOpStore = 0,
        AttachmentStoreOpDontCare = 1,
    }

    public enum VkBlendFactor : int {
        BlendFactorZero = 0,
        BlendFactorOne = 1,
        BlendFactorSrcColor = 2,
        BlendFactorOneMinusSrcColor = 3,
        BlendFactorDstColor = 4,
        BlendFactorOneMinusDstColor = 5,
        BlendFactorSrcAlpha = 6,
        BlendFactorOneMinusSrcAlpha = 7,
        BlendFactorDstAlpha = 8,
        BlendFactorOneMinusDstAlpha = 9,
        BlendFactorConstantColor = 10,
        BlendFactorOneMinusConstantColor = 11,
        BlendFactorConstantAlpha = 12,
        BlendFactorOneMinusConstantAlpha = 13,
        BlendFactorSrcAlphaSaturate = 14,
        BlendFactorSrc1Color = 15,
        BlendFactorOneMinusSrc1Color = 16,
        BlendFactorSrc1Alpha = 17,
        BlendFactorOneMinusSrc1Alpha = 18,
    }

    public enum VkBlendOp : int {
        BlendOpAdd = 0,
        BlendOpSubtract = 1,
        BlendOpReverseSubtract = 2,
        BlendOpMin = 3,
        BlendOpMax = 4,
        BlendOpZeroExt = 1000148000,
        BlendOpSrcExt = 1000148001,
        BlendOpDstExt = 1000148002,
        BlendOpSrcOverExt = 1000148003,
        BlendOpDstOverExt = 1000148004,
        BlendOpSrcInExt = 1000148005,
        BlendOpDstInExt = 1000148006,
        BlendOpSrcOutExt = 1000148007,
        BlendOpDstOutExt = 1000148008,
        BlendOpSrcAtopExt = 1000148009,
        BlendOpDstAtopExt = 1000148010,
        BlendOpXorExt = 1000148011,
        BlendOpMultiplyExt = 1000148012,
        BlendOpScreenExt = 1000148013,
        BlendOpOverlayExt = 1000148014,
        BlendOpDarkenExt = 1000148015,
        BlendOpLightenExt = 1000148016,
        BlendOpColordodgeExt = 1000148017,
        BlendOpColorburnExt = 1000148018,
        BlendOpHardlightExt = 1000148019,
        BlendOpSoftlightExt = 1000148020,
        BlendOpDifferenceExt = 1000148021,
        BlendOpExclusionExt = 1000148022,
        BlendOpInvertExt = 1000148023,
        BlendOpInvertRgbExt = 1000148024,
        BlendOpLineardodgeExt = 1000148025,
        BlendOpLinearburnExt = 1000148026,
        BlendOpVividlightExt = 1000148027,
        BlendOpLinearlightExt = 1000148028,
        BlendOpPinlightExt = 1000148029,
        BlendOpHardmixExt = 1000148030,
        BlendOpHslHueExt = 1000148031,
        BlendOpHslSaturationExt = 1000148032,
        BlendOpHslColorExt = 1000148033,
        BlendOpHslLuminosityExt = 1000148034,
        BlendOpPlusExt = 1000148035,
        BlendOpPlusClampedExt = 1000148036,
        BlendOpPlusClampedAlphaExt = 1000148037,
        BlendOpPlusDarkerExt = 1000148038,
        BlendOpMinusExt = 1000148039,
        BlendOpMinusClampedExt = 1000148040,
        BlendOpContrastExt = 1000148041,
        BlendOpInvertOvgExt = 1000148042,
        BlendOpRedExt = 1000148043,
        BlendOpGreenExt = 1000148044,
        BlendOpBlueExt = 1000148045,
    }

    public enum VkBorderColor : int {
        BorderColorFloatTransparentBlack = 0,
        BorderColorIntTransparentBlack = 1,
        BorderColorFloatOpaqueBlack = 2,
        BorderColorIntOpaqueBlack = 3,
        BorderColorFloatOpaqueWhite = 4,
        BorderColorIntOpaqueWhite = 5,
    }

    public enum VkPipelineCacheHeaderVersion : int {
        PipelineCacheHeaderVersionOne = 1,
    }

    [Flags]
    public enum VkDescriptorSetLayoutCreateFlags : int {
        DescriptorSetLayoutCreatePushDescriptorKhr = 0x1,
    }

    [Flags]
    public enum VkBufferCreateFlags : int {
        BufferCreateSparseBinding = 0x1,
        BufferCreateSparseResidency = 0x2,
        BufferCreateSparseAliased = 0x4,
    }

    [Flags]
    public enum VkBufferUsageFlags : int {
        BufferUsageTransferSrc = 0x1,
        BufferUsageTransferDst = 0x2,
        BufferUsageUniformTexelBuffer = 0x4,
        BufferUsageStorageTexelBuffer = 0x8,
        BufferUsageUniformBuffer = 0x10,
        BufferUsageStorageBuffer = 0x20,
        BufferUsageIndexBuffer = 0x40,
        BufferUsageVertexBuffer = 0x80,
        BufferUsageIndirectBuffer = 0x100,
    }

    [Flags]
    public enum VkColorComponentFlags : int {
        ColorComponentR = 0x1,
        ColorComponentG = 0x2,
        ColorComponentB = 0x4,
        ColorComponentA = 0x8,
    }

    public enum VkComponentSwizzle : int {
        ComponentSwizzleIdentity = 0,
        ComponentSwizzleZero = 1,
        ComponentSwizzleOne = 2,
        ComponentSwizzleR = 3,
        ComponentSwizzleG = 4,
        ComponentSwizzleB = 5,
        ComponentSwizzleA = 6,
    }

    [Flags]
    public enum VkCommandPoolCreateFlags : int {
        CommandPoolCreateTransient = 0x1,
        CommandPoolCreateResetCommandBuffer = 0x2,
    }

    [Flags]
    public enum VkCommandPoolResetFlags : int {
        CommandPoolResetReleaseResources = 0x1,
    }

    [Flags]
    public enum VkCommandBufferResetFlags : int {
        CommandBufferResetReleaseResources = 0x1,
    }

    public enum VkCommandBufferLevel : int {
        CommandBufferLevelPrimary = 0,
        CommandBufferLevelSecondary = 1,
    }

    [Flags]
    public enum VkCommandBufferUsageFlags : int {
        CommandBufferUsageOneTimeSubmit = 0x1,
        CommandBufferUsageRenderPassContinue = 0x2,
        CommandBufferUsageSimultaneousUse = 0x4,
    }

    public enum VkCompareOp : int {
        CompareOpNever = 0,
        CompareOpLess = 1,
        CompareOpEqual = 2,
        CompareOpLessOrEqual = 3,
        CompareOpGreater = 4,
        CompareOpNotEqual = 5,
        CompareOpGreaterOrEqual = 6,
        CompareOpAlways = 7,
    }

    [Flags]
    public enum VkCullModeFlags : int {
        CullModeNone = 0,
        CullModeFront = 0x1,
        CullModeBack = 0x2,
        CullModeFrontAndBack = 0x00000003,
    }

    public enum VkDescriptorType : int {
        DescriptorTypeSampler = 0,
        DescriptorTypeCombinedImageSampler = 1,
        DescriptorTypeSampledImage = 2,
        DescriptorTypeStorageImage = 3,
        DescriptorTypeUniformTexelBuffer = 4,
        DescriptorTypeStorageTexelBuffer = 5,
        DescriptorTypeUniformBuffer = 6,
        DescriptorTypeStorageBuffer = 7,
        DescriptorTypeUniformBufferDynamic = 8,
        DescriptorTypeStorageBufferDynamic = 9,
        DescriptorTypeInputAttachment = 10,
    }

    public enum VkDynamicState : int {
        DynamicStateViewport = 0,
        DynamicStateScissor = 1,
        DynamicStateLineWidth = 2,
        DynamicStateDepthBias = 3,
        DynamicStateBlendConstants = 4,
        DynamicStateDepthBounds = 5,
        DynamicStateStencilCompareMask = 6,
        DynamicStateStencilWriteMask = 7,
        DynamicStateStencilReference = 8,
        DynamicStateViewportWScalingNv = 1000087000,
        DynamicStateDiscardRectangleExt = 1000099000,
        DynamicStateSampleLocationsExt = 1000143000,
    }

    [Flags]
    public enum VkFenceCreateFlags : int {
        FenceCreateSignaled = 0x1,
    }

    public enum VkPolygonMode : int {
        PolygonModeFill = 0,
        PolygonModeLine = 1,
        PolygonModePoint = 2,
        PolygonModeFillRectangleNv = 1000153000,
    }

    public enum VkFormat : int {
        FormatUndefined = 0,
        FormatR4G4UnormPack8 = 1,
        FormatR4G4B4A4UnormPack16 = 2,
        FormatB4G4R4A4UnormPack16 = 3,
        FormatR5G6B5UnormPack16 = 4,
        FormatB5G6R5UnormPack16 = 5,
        FormatR5G5B5A1UnormPack16 = 6,
        FormatB5G5R5A1UnormPack16 = 7,
        FormatA1R5G5B5UnormPack16 = 8,
        FormatR8Unorm = 9,
        FormatR8Snorm = 10,
        FormatR8Uscaled = 11,
        FormatR8Sscaled = 12,
        FormatR8Uint = 13,
        FormatR8Sint = 14,
        FormatR8Srgb = 15,
        FormatR8G8Unorm = 16,
        FormatR8G8Snorm = 17,
        FormatR8G8Uscaled = 18,
        FormatR8G8Sscaled = 19,
        FormatR8G8Uint = 20,
        FormatR8G8Sint = 21,
        FormatR8G8Srgb = 22,
        FormatR8G8B8Unorm = 23,
        FormatR8G8B8Snorm = 24,
        FormatR8G8B8Uscaled = 25,
        FormatR8G8B8Sscaled = 26,
        FormatR8G8B8Uint = 27,
        FormatR8G8B8Sint = 28,
        FormatR8G8B8Srgb = 29,
        FormatB8G8R8Unorm = 30,
        FormatB8G8R8Snorm = 31,
        FormatB8G8R8Uscaled = 32,
        FormatB8G8R8Sscaled = 33,
        FormatB8G8R8Uint = 34,
        FormatB8G8R8Sint = 35,
        FormatB8G8R8Srgb = 36,
        FormatR8G8B8A8Unorm = 37,
        FormatR8G8B8A8Snorm = 38,
        FormatR8G8B8A8Uscaled = 39,
        FormatR8G8B8A8Sscaled = 40,
        FormatR8G8B8A8Uint = 41,
        FormatR8G8B8A8Sint = 42,
        FormatR8G8B8A8Srgb = 43,
        FormatB8G8R8A8Unorm = 44,
        FormatB8G8R8A8Snorm = 45,
        FormatB8G8R8A8Uscaled = 46,
        FormatB8G8R8A8Sscaled = 47,
        FormatB8G8R8A8Uint = 48,
        FormatB8G8R8A8Sint = 49,
        FormatB8G8R8A8Srgb = 50,
        FormatA8B8G8R8UnormPack32 = 51,
        FormatA8B8G8R8SnormPack32 = 52,
        FormatA8B8G8R8UscaledPack32 = 53,
        FormatA8B8G8R8SscaledPack32 = 54,
        FormatA8B8G8R8UintPack32 = 55,
        FormatA8B8G8R8SintPack32 = 56,
        FormatA8B8G8R8SrgbPack32 = 57,
        FormatA2R10G10B10UnormPack32 = 58,
        FormatA2R10G10B10SnormPack32 = 59,
        FormatA2R10G10B10UscaledPack32 = 60,
        FormatA2R10G10B10SscaledPack32 = 61,
        FormatA2R10G10B10UintPack32 = 62,
        FormatA2R10G10B10SintPack32 = 63,
        FormatA2B10G10R10UnormPack32 = 64,
        FormatA2B10G10R10SnormPack32 = 65,
        FormatA2B10G10R10UscaledPack32 = 66,
        FormatA2B10G10R10SscaledPack32 = 67,
        FormatA2B10G10R10UintPack32 = 68,
        FormatA2B10G10R10SintPack32 = 69,
        FormatR16Unorm = 70,
        FormatR16Snorm = 71,
        FormatR16Uscaled = 72,
        FormatR16Sscaled = 73,
        FormatR16Uint = 74,
        FormatR16Sint = 75,
        FormatR16Sfloat = 76,
        FormatR16G16Unorm = 77,
        FormatR16G16Snorm = 78,
        FormatR16G16Uscaled = 79,
        FormatR16G16Sscaled = 80,
        FormatR16G16Uint = 81,
        FormatR16G16Sint = 82,
        FormatR16G16Sfloat = 83,
        FormatR16G16B16Unorm = 84,
        FormatR16G16B16Snorm = 85,
        FormatR16G16B16Uscaled = 86,
        FormatR16G16B16Sscaled = 87,
        FormatR16G16B16Uint = 88,
        FormatR16G16B16Sint = 89,
        FormatR16G16B16Sfloat = 90,
        FormatR16G16B16A16Unorm = 91,
        FormatR16G16B16A16Snorm = 92,
        FormatR16G16B16A16Uscaled = 93,
        FormatR16G16B16A16Sscaled = 94,
        FormatR16G16B16A16Uint = 95,
        FormatR16G16B16A16Sint = 96,
        FormatR16G16B16A16Sfloat = 97,
        FormatR32Uint = 98,
        FormatR32Sint = 99,
        FormatR32Sfloat = 100,
        FormatR32G32Uint = 101,
        FormatR32G32Sint = 102,
        FormatR32G32Sfloat = 103,
        FormatR32G32B32Uint = 104,
        FormatR32G32B32Sint = 105,
        FormatR32G32B32Sfloat = 106,
        FormatR32G32B32A32Uint = 107,
        FormatR32G32B32A32Sint = 108,
        FormatR32G32B32A32Sfloat = 109,
        FormatR64Uint = 110,
        FormatR64Sint = 111,
        FormatR64Sfloat = 112,
        FormatR64G64Uint = 113,
        FormatR64G64Sint = 114,
        FormatR64G64Sfloat = 115,
        FormatR64G64B64Uint = 116,
        FormatR64G64B64Sint = 117,
        FormatR64G64B64Sfloat = 118,
        FormatR64G64B64A64Uint = 119,
        FormatR64G64B64A64Sint = 120,
        FormatR64G64B64A64Sfloat = 121,
        FormatB10G11R11UfloatPack32 = 122,
        FormatE5B9G9R9UfloatPack32 = 123,
        FormatD16Unorm = 124,
        FormatX8D24UnormPack32 = 125,
        FormatD32Sfloat = 126,
        FormatS8Uint = 127,
        FormatD16UnormS8Uint = 128,
        FormatD24UnormS8Uint = 129,
        FormatD32SfloatS8Uint = 130,
        FormatBc1RgbUnormBlock = 131,
        FormatBc1RgbSrgbBlock = 132,
        FormatBc1RgbaUnormBlock = 133,
        FormatBc1RgbaSrgbBlock = 134,
        FormatBc2UnormBlock = 135,
        FormatBc2SrgbBlock = 136,
        FormatBc3UnormBlock = 137,
        FormatBc3SrgbBlock = 138,
        FormatBc4UnormBlock = 139,
        FormatBc4SnormBlock = 140,
        FormatBc5UnormBlock = 141,
        FormatBc5SnormBlock = 142,
        FormatBc6HUfloatBlock = 143,
        FormatBc6HSfloatBlock = 144,
        FormatBc7UnormBlock = 145,
        FormatBc7SrgbBlock = 146,
        FormatEtc2R8G8B8UnormBlock = 147,
        FormatEtc2R8G8B8SrgbBlock = 148,
        FormatEtc2R8G8B8A1UnormBlock = 149,
        FormatEtc2R8G8B8A1SrgbBlock = 150,
        FormatEtc2R8G8B8A8UnormBlock = 151,
        FormatEtc2R8G8B8A8SrgbBlock = 152,
        FormatEacR11UnormBlock = 153,
        FormatEacR11SnormBlock = 154,
        FormatEacR11G11UnormBlock = 155,
        FormatEacR11G11SnormBlock = 156,
        FormatAstc4X4UnormBlock = 157,
        FormatAstc4X4SrgbBlock = 158,
        FormatAstc5X4UnormBlock = 159,
        FormatAstc5X4SrgbBlock = 160,
        FormatAstc5X5UnormBlock = 161,
        FormatAstc5X5SrgbBlock = 162,
        FormatAstc6X5UnormBlock = 163,
        FormatAstc6X5SrgbBlock = 164,
        FormatAstc6X6UnormBlock = 165,
        FormatAstc6X6SrgbBlock = 166,
        FormatAstc8X5UnormBlock = 167,
        FormatAstc8X5SrgbBlock = 168,
        FormatAstc8X6UnormBlock = 169,
        FormatAstc8X6SrgbBlock = 170,
        FormatAstc8X8UnormBlock = 171,
        FormatAstc8X8SrgbBlock = 172,
        FormatAstc10X5UnormBlock = 173,
        FormatAstc10X5SrgbBlock = 174,
        FormatAstc10X6UnormBlock = 175,
        FormatAstc10X6SrgbBlock = 176,
        FormatAstc10X8UnormBlock = 177,
        FormatAstc10X8SrgbBlock = 178,
        FormatAstc10X10UnormBlock = 179,
        FormatAstc10X10SrgbBlock = 180,
        FormatAstc12X10UnormBlock = 181,
        FormatAstc12X10SrgbBlock = 182,
        FormatAstc12X12UnormBlock = 183,
        FormatAstc12X12SrgbBlock = 184,
        FormatPvrtc12BppUnormBlockImg = 1000054000,
        FormatPvrtc14BppUnormBlockImg = 1000054001,
        FormatPvrtc22BppUnormBlockImg = 1000054002,
        FormatPvrtc24BppUnormBlockImg = 1000054003,
        FormatPvrtc12BppSrgbBlockImg = 1000054004,
        FormatPvrtc14BppSrgbBlockImg = 1000054005,
        FormatPvrtc22BppSrgbBlockImg = 1000054006,
        FormatPvrtc24BppSrgbBlockImg = 1000054007,
        FormatG8B8G8R8422UnormKhr = 1000156000,
        FormatB8G8R8G8422UnormKhr = 1000156001,
        FormatG8B8R83Plane420UnormKhr = 1000156002,
        FormatG8B8R82Plane420UnormKhr = 1000156003,
        FormatG8B8R83Plane422UnormKhr = 1000156004,
        FormatG8B8R82Plane422UnormKhr = 1000156005,
        FormatG8B8R83Plane444UnormKhr = 1000156006,
        FormatR10X6UnormPack16Khr = 1000156007,
        FormatR10X6G10X6Unorm2Pack16Khr = 1000156008,
        FormatR10X6G10X6B10X6A10X6Unorm4Pack16Khr = 1000156009,
        FormatG10X6B10X6G10X6R10X6422Unorm4Pack16Khr = 1000156010,
        FormatB10X6G10X6R10X6G10X6422Unorm4Pack16Khr = 1000156011,
        FormatG10X6B10X6R10X63Plane420Unorm3Pack16Khr = 1000156012,
        FormatG10X6B10X6R10X62Plane420Unorm3Pack16Khr = 1000156013,
        FormatG10X6B10X6R10X63Plane422Unorm3Pack16Khr = 1000156014,
        FormatG10X6B10X6R10X62Plane422Unorm3Pack16Khr = 1000156015,
        FormatG10X6B10X6R10X63Plane444Unorm3Pack16Khr = 1000156016,
        FormatR12X4UnormPack16Khr = 1000156017,
        FormatR12X4G12X4Unorm2Pack16Khr = 1000156018,
        FormatR12X4G12X4B12X4A12X4Unorm4Pack16Khr = 1000156019,
        FormatG12X4B12X4G12X4R12X4422Unorm4Pack16Khr = 1000156020,
        FormatB12X4G12X4R12X4G12X4422Unorm4Pack16Khr = 1000156021,
        FormatG12X4B12X4R12X43Plane420Unorm3Pack16Khr = 1000156022,
        FormatG12X4B12X4R12X42Plane420Unorm3Pack16Khr = 1000156023,
        FormatG12X4B12X4R12X43Plane422Unorm3Pack16Khr = 1000156024,
        FormatG12X4B12X4R12X42Plane422Unorm3Pack16Khr = 1000156025,
        FormatG12X4B12X4R12X43Plane444Unorm3Pack16Khr = 1000156026,
        FormatG16B16G16R16422UnormKhr = 1000156027,
        FormatB16G16R16G16422UnormKhr = 1000156028,
        FormatG16B16R163Plane420UnormKhr = 1000156029,
        FormatG16B16R162Plane420UnormKhr = 1000156030,
        FormatG16B16R163Plane422UnormKhr = 1000156031,
        FormatG16B16R162Plane422UnormKhr = 1000156032,
        FormatG16B16R163Plane444UnormKhr = 1000156033,
    }

    [Flags]
    public enum VkFormatFeatureFlags : int {
        FormatFeatureSampledImage = 0x1,
        FormatFeatureStorageImage = 0x2,
        FormatFeatureStorageImageAtomic = 0x4,
        FormatFeatureUniformTexelBuffer = 0x8,
        FormatFeatureStorageTexelBuffer = 0x10,
        FormatFeatureStorageTexelBufferAtomic = 0x20,
        FormatFeatureVertexBuffer = 0x40,
        FormatFeatureColorAttachment = 0x80,
        FormatFeatureColorAttachmentBlend = 0x100,
        FormatFeatureDepthStencilAttachment = 0x200,
        FormatFeatureBlitSrc = 0x400,
        FormatFeatureBlitDst = 0x800,
        FormatFeatureSampledImageFilterLinear = 0x1000,
        FormatFeatureSampledImageFilterCubicImg = 0x2000,
        FormatFeatureTransferSrcKhr = 0x4000,
        FormatFeatureTransferDstKhr = 0x8000,
        FormatFeatureSampledImageFilterMinmaxExt = 0x10000,
        FormatFeatureMidpointChromaSamplesKhr = 0x20000,
        FormatFeatureSampledImageYcbcrConversionLinearFilterKhr = 0x40000,
        FormatFeatureSampledImageYcbcrConversionSeparateReconstructionFilterKhr = 0x80000,
        FormatFeatureSampledImageYcbcrConversionChromaReconstructionExplicitKhr = 0x100000,
        FormatFeatureSampledImageYcbcrConversionChromaReconstructionExplicitForceableKhr = 0x200000,
        FormatFeatureDisjointKhr = 0x400000,
        FormatFeatureCositedChromaSamplesKhr = 0x800000,
    }

    public enum VkFrontFace : int {
        FrontFaceCounterClockwise = 0,
        FrontFaceClockwise = 1,
    }

    [Flags]
    public enum VkImageAspectFlags : int {
        ImageAspectColor = 0x1,
        ImageAspectDepth = 0x2,
        ImageAspectStencil = 0x4,
        ImageAspectMetadata = 0x8,
        ImageAspectPlane0Khr = 0x10,
        ImageAspectPlane1Khr = 0x20,
        ImageAspectPlane2Khr = 0x40,
    }

    [Flags]
    public enum VkImageCreateFlags : int {
        ImageCreateSparseBinding = 0x1,
        ImageCreateSparseResidency = 0x2,
        ImageCreateSparseAliased = 0x4,
        ImageCreateMutableFormat = 0x8,
        ImageCreateCubeCompatible = 0x10,
        ImageCreateBindSfrKhx = 0x40,
        ImageCreate2DArrayCompatibleKhr = 0x20,
        ImageCreateBlockTexelViewCompatibleKhr = 0x80,
        ImageCreateExtendedUsageKhr = 0x100,
        ImageCreateSampleLocationsCompatibleDepthExt = 0x1000,
        ImageCreateDisjointKhr = 0x200,
        ImageCreateAliasKhr = 0x400,
    }

    public enum VkImageLayout : int {
        ImageLayoutUndefined = 0,
        ImageLayoutGeneral = 1,
        ImageLayoutColorAttachmentOptimal = 2,
        ImageLayoutDepthStencilAttachmentOptimal = 3,
        ImageLayoutDepthStencilReadOnlyOptimal = 4,
        ImageLayoutShaderReadOnlyOptimal = 5,
        ImageLayoutTransferSrcOptimal = 6,
        ImageLayoutTransferDstOptimal = 7,
        ImageLayoutPreinitialized = 8,
        ImageLayoutPresentSrcKhr = 1000001002,
        ImageLayoutSharedPresentKhr = 1000111000,
        ImageLayoutDepthReadOnlyStencilAttachmentOptimalKhr = 1000117000,
        ImageLayoutDepthAttachmentStencilReadOnlyOptimalKhr = 1000117001,
    }

    public enum VkImageTiling : int {
        ImageTilingOptimal = 0,
        ImageTilingLinear = 1,
    }

    public enum VkImageType : int {
        ImageType1D = 0,
        ImageType2D = 1,
        ImageType3D = 2,
    }

    [Flags]
    public enum VkImageUsageFlags : int {
        ImageUsageTransferSrc = 0x1,
        ImageUsageTransferDst = 0x2,
        ImageUsageSampled = 0x4,
        ImageUsageStorage = 0x8,
        ImageUsageColorAttachment = 0x10,
        ImageUsageDepthStencilAttachment = 0x20,
        ImageUsageTransientAttachment = 0x40,
        ImageUsageInputAttachment = 0x80,
    }

    public enum VkImageViewType : int {
        ImageViewType1D = 0,
        ImageViewType2D = 1,
        ImageViewType3D = 2,
        ImageViewTypeCube = 3,
        ImageViewType1DArray = 4,
        ImageViewType2DArray = 5,
        ImageViewTypeCubeArray = 6,
    }

    public enum VkSharingMode : int {
        SharingModeExclusive = 0,
        SharingModeConcurrent = 1,
    }

    public enum VkIndexType : int {
        IndexTypeUint16 = 0,
        IndexTypeUint32 = 1,
    }

    public enum VkLogicOp : int {
        LogicOpClear = 0,
        LogicOpAnd = 1,
        LogicOpAndReverse = 2,
        LogicOpCopy = 3,
        LogicOpAndInverted = 4,
        LogicOpNoOp = 5,
        LogicOpXor = 6,
        LogicOpOr = 7,
        LogicOpNor = 8,
        LogicOpEquivalent = 9,
        LogicOpInvert = 10,
        LogicOpOrReverse = 11,
        LogicOpCopyInverted = 12,
        LogicOpOrInverted = 13,
        LogicOpNand = 14,
        LogicOpSet = 15,
    }

    [Flags]
    public enum VkMemoryHeapFlags : int {
        MemoryHeapDeviceLocal = 0x1,
        MemoryHeapMultiInstanceKhx = 0x2,
    }

    [Flags]
    public enum VkAccessFlags : int {
        AccessIndirectCommandRead = 0x1,
        AccessIndexRead = 0x2,
        AccessVertexAttributeRead = 0x4,
        AccessUniformRead = 0x8,
        AccessInputAttachmentRead = 0x10,
        AccessShaderRead = 0x20,
        AccessShaderWrite = 0x40,
        AccessColorAttachmentRead = 0x80,
        AccessColorAttachmentWrite = 0x100,
        AccessDepthStencilAttachmentRead = 0x200,
        AccessDepthStencilAttachmentWrite = 0x400,
        AccessTransferRead = 0x800,
        AccessTransferWrite = 0x1000,
        AccessHostRead = 0x2000,
        AccessHostWrite = 0x4000,
        AccessMemoryRead = 0x8000,
        AccessMemoryWrite = 0x10000,
        AccessCommandProcessReadNvx = 0x20000,
        AccessCommandProcessWriteNvx = 0x40000,
        AccessColorAttachmentReadNoncoherentExt = 0x80000,
    }

    [Flags]
    public enum VkMemoryPropertyFlags : int {
        MemoryPropertyDeviceLocal = 0x1,
        MemoryPropertyHostVisible = 0x2,
        MemoryPropertyHostCoherent = 0x4,
        MemoryPropertyHostCached = 0x8,
        MemoryPropertyLazilyAllocated = 0x10,
    }

    public enum VkPhysicalDeviceType : int {
        PhysicalDeviceTypeOther = 0,
        PhysicalDeviceTypeIntegratedGpu = 1,
        PhysicalDeviceTypeDiscreteGpu = 2,
        PhysicalDeviceTypeVirtualGpu = 3,
        PhysicalDeviceTypeCpu = 4,
    }

    public enum VkPipelineBindPoint : int {
        PipelineBindPointGraphics = 0,
        PipelineBindPointCompute = 1,
    }

    [Flags]
    public enum VkPipelineCreateFlags : int {
        PipelineCreateDisableOptimization = 0x1,
        PipelineCreateAllowDerivatives = 0x2,
        PipelineCreateDerivative = 0x4,
        PipelineCreateViewIndexFromDeviceIndexKhx = 0x8,
        PipelineCreateDispatchBaseKhx = 0x10,
    }

    public enum VkPrimitiveTopology : int {
        PrimitiveTopologyPointList = 0,
        PrimitiveTopologyLineList = 1,
        PrimitiveTopologyLineStrip = 2,
        PrimitiveTopologyTriangleList = 3,
        PrimitiveTopologyTriangleStrip = 4,
        PrimitiveTopologyTriangleFan = 5,
        PrimitiveTopologyLineListWithAdjacency = 6,
        PrimitiveTopologyLineStripWithAdjacency = 7,
        PrimitiveTopologyTriangleListWithAdjacency = 8,
        PrimitiveTopologyTriangleStripWithAdjacency = 9,
        PrimitiveTopologyPatchList = 10,
    }

    [Flags]
    public enum VkQueryControlFlags : int {
        QueryControlPrecise = 0x1,
    }

    [Flags]
    public enum VkQueryPipelineStatisticFlags : int {
        QueryPipelineStatisticInputAssemblyVertices = 0x1,
        QueryPipelineStatisticInputAssemblyPrimitives = 0x2,
        QueryPipelineStatisticVertexShaderInvocations = 0x4,
        QueryPipelineStatisticGeometryShaderInvocations = 0x8,
        QueryPipelineStatisticGeometryShaderPrimitives = 0x10,
        QueryPipelineStatisticClippingInvocations = 0x20,
        QueryPipelineStatisticClippingPrimitives = 0x40,
        QueryPipelineStatisticFragmentShaderInvocations = 0x80,
        QueryPipelineStatisticTessellationControlShaderPatches = 0x100,
        QueryPipelineStatisticTessellationEvaluationShaderInvocations = 0x200,
        QueryPipelineStatisticComputeShaderInvocations = 0x400,
    }

    [Flags]
    public enum VkQueryResultFlags : int {
        QueryResult64 = 0x1,
        QueryResultWait = 0x2,
        QueryResultWithAvailability = 0x4,
        QueryResultPartial = 0x8,
    }

    public enum VkQueryType : int {
        QueryTypeOcclusion = 0,
        QueryTypePipelineStatistics = 1,
        QueryTypeTimestamp = 2,
    }

    [Flags]
    public enum VkQueueFlags : int {
        QueueGraphics = 0x1,
        QueueCompute = 0x2,
        QueueTransfer = 0x4,
        QueueSparseBinding = 0x8,
    }

    public enum VkSubpassContents : int {
        SubpassContentsInline = 0,
        SubpassContentsSecondaryCommandBuffers = 1,
    }

    public enum VkResult : int {
        Success = 0,
        NotReady = 1,
        Timeout = 2,
        EventSet = 3,
        EventReset = 4,
        Incomplete = 5,
        ErrorOutOfHostMemory = -1,
        ErrorOutOfDeviceMemory = -2,
        ErrorInitializationFailed = -3,
        ErrorDeviceLost = -4,
        ErrorMemoryMapFailed = -5,
        ErrorLayerNotPresent = -6,
        ErrorExtensionNotPresent = -7,
        ErrorFeatureNotPresent = -8,
        ErrorIncompatibleDriver = -9,
        ErrorTooManyObjects = -10,
        ErrorFormatNotSupported = -11,
        ErrorFragmentedPool = -12,
        ErrorSurfaceLostKhr = -1000000000,
        ErrorNativeWindowInUseKhr = -1000000001,
        SuboptimalKhr = 1000001003,
        ErrorOutOfDateKhr = -1000001004,
        ErrorIncompatibleDisplayKhr = -1000003001,
        ErrorValidationFailedExt = -1000011001,
        ErrorInvalidShaderNv = -1000012000,
        ErrorOutOfPoolMemoryKhr = -1000069000,
        ErrorInvalidExternalHandleKhr = -1000072003,
        ErrorNotPermittedExt = -1000174001,
    }

    [Flags]
    public enum VkShaderStageFlags : int {
        ShaderStageVertex = 0x1,
        ShaderStageTessellationControl = 0x2,
        ShaderStageTessellationEvaluation = 0x4,
        ShaderStageGeometry = 0x8,
        ShaderStageFragment = 0x10,
        ShaderStageCompute = 0x20,
        ShaderStageAllGraphics = 0x0000001F,
        ShaderStageAll = 0x7FFFFFFF,
    }

    [Flags]
    public enum VkSparseMemoryBindFlags : int {
        SparseMemoryBindMetadata = 0x1,
    }

    [Flags]
    public enum VkStencilFaceFlags : int {
        StencilFaceFront = 0x1,
        StencilFaceBack = 0x2,
        StencilFrontAndBack = 0x00000003,
    }

    public enum VkStencilOp : int {
        StencilOpKeep = 0,
        StencilOpZero = 1,
        StencilOpReplace = 2,
        StencilOpIncrementAndClamp = 3,
        StencilOpDecrementAndClamp = 4,
        StencilOpInvert = 5,
        StencilOpIncrementAndWrap = 6,
        StencilOpDecrementAndWrap = 7,
    }

    public enum VkStructureType : int {
        ApplicationInfo = 0,
        InstanceCreateInfo = 1,
        DeviceQueueCreateInfo = 2,
        DeviceCreateInfo = 3,
        SubmitInfo = 4,
        MemoryAllocateInfo = 5,
        MappedMemoryRange = 6,
        BindSparseInfo = 7,
        FenceCreateInfo = 8,
        SemaphoreCreateInfo = 9,
        EventCreateInfo = 10,
        QueryPoolCreateInfo = 11,
        BufferCreateInfo = 12,
        BufferViewCreateInfo = 13,
        ImageCreateInfo = 14,
        ImageViewCreateInfo = 15,
        ShaderModuleCreateInfo = 16,
        PipelineCacheCreateInfo = 17,
        PipelineShaderStageCreateInfo = 18,
        PipelineVertexInputStateCreateInfo = 19,
        PipelineInputAssemblyStateCreateInfo = 20,
        PipelineTessellationStateCreateInfo = 21,
        PipelineViewportStateCreateInfo = 22,
        PipelineRasterizationStateCreateInfo = 23,
        PipelineMultisampleStateCreateInfo = 24,
        PipelineDepthStencilStateCreateInfo = 25,
        PipelineColorBlendStateCreateInfo = 26,
        PipelineDynamicStateCreateInfo = 27,
        GraphicsPipelineCreateInfo = 28,
        ComputePipelineCreateInfo = 29,
        PipelineLayoutCreateInfo = 30,
        SamplerCreateInfo = 31,
        DescriptorSetLayoutCreateInfo = 32,
        DescriptorPoolCreateInfo = 33,
        DescriptorSetAllocateInfo = 34,
        WriteDescriptorSet = 35,
        CopyDescriptorSet = 36,
        FramebufferCreateInfo = 37,
        RenderPassCreateInfo = 38,
        CommandPoolCreateInfo = 39,
        CommandBufferAllocateInfo = 40,
        CommandBufferInheritanceInfo = 41,
        CommandBufferBeginInfo = 42,
        RenderPassBeginInfo = 43,
        BufferMemoryBarrier = 44,
        ImageMemoryBarrier = 45,
        MemoryBarrier = 46,
        LoaderInstanceCreateInfo = 47,
        LoaderDeviceCreateInfo = 48,
        SwapchainCreateInfoKhr = 1000001000,
        PresentInfoKhr = 1000001001,
        DisplayModeCreateInfoKhr = 1000002000,
        DisplaySurfaceCreateInfoKhr = 1000002001,
        DisplayPresentInfoKhr = 1000003000,
        XlibSurfaceCreateInfoKhr = 1000004000,
        XcbSurfaceCreateInfoKhr = 1000005000,
        WaylandSurfaceCreateInfoKhr = 1000006000,
        MirSurfaceCreateInfoKhr = 1000007000,
        AndroidSurfaceCreateInfoKhr = 1000008000,
        Win32SurfaceCreateInfoKhr = 1000009000,
        DebugReportCallbackCreateInfoExt = 1000011000,
        PipelineRasterizationStateRasterizationOrderAmd = 1000018000,
        DebugMarkerObjectNameInfoExt = 1000022000,
        DebugMarkerObjectTagInfoExt = 1000022001,
        DebugMarkerMarkerInfoExt = 1000022002,
        DedicatedAllocationImageCreateInfoNv = 1000026000,
        DedicatedAllocationBufferCreateInfoNv = 1000026001,
        DedicatedAllocationMemoryAllocateInfoNv = 1000026002,
        TextureLODGatherFormatPropertiesAmd = 1000041000,
        RenderPassMultiviewCreateInfoKhx = 1000053000,
        PhysicalDeviceMultiviewFeaturesKhx = 1000053001,
        PhysicalDeviceMultiviewPropertiesKhx = 1000053002,
        ExternalMemoryImageCreateInfoNv = 1000056000,
        ExportMemoryAllocateInfoNv = 1000056001,
        ImportMemoryWin32HandleInfoNv = 1000057000,
        ExportMemoryWin32HandleInfoNv = 1000057001,
        Win32KeyedMutexAcquireReleaseInfoNv = 1000058000,
        PhysicalDeviceFeatures2Khr = 1000059000,
        PhysicalDeviceProperties2Khr = 1000059001,
        FormatProperties2Khr = 1000059002,
        ImageFormatProperties2Khr = 1000059003,
        PhysicalDeviceImageFormatInfo2Khr = 1000059004,
        QueueFamilyProperties2Khr = 1000059005,
        PhysicalDeviceMemoryProperties2Khr = 1000059006,
        SparseImageFormatProperties2Khr = 1000059007,
        PhysicalDeviceSparseImageFormatInfo2Khr = 1000059008,
        MemoryAllocateFlagsInfoKhx = 1000060000,
        DeviceGroupRenderPassBeginInfoKhx = 1000060003,
        DeviceGroupCommandBufferBeginInfoKhx = 1000060004,
        DeviceGroupSubmitInfoKhx = 1000060005,
        DeviceGroupBindSparseInfoKhx = 1000060006,
        AcquireNextImageInfoKhx = 1000060010,
        BindBufferMemoryDeviceGroupInfoKhx = 1000060013,
        BindImageMemoryDeviceGroupInfoKhx = 1000060014,
        DeviceGroupPresentCapabilitiesKhx = 1000060007,
        ImageSwapchainCreateInfoKhx = 1000060008,
        BindImageMemorySwapchainInfoKhx = 1000060009,
        DeviceGroupPresentInfoKhx = 1000060011,
        DeviceGroupSwapchainCreateInfoKhx = 1000060012,
        ValidationFlagsExt = 1000061000,
        ViSurfaceCreateInfoNn = 1000062000,
        PhysicalDeviceGroupPropertiesKhx = 1000070000,
        DeviceGroupDeviceCreateInfoKhx = 1000070001,
        PhysicalDeviceExternalImageFormatInfoKhr = 1000071000,
        ExternalImageFormatPropertiesKhr = 1000071001,
        PhysicalDeviceExternalBufferInfoKhr = 1000071002,
        ExternalBufferPropertiesKhr = 1000071003,
        PhysicalDeviceIDPropertiesKhr = 1000071004,
        ExternalMemoryBufferCreateInfoKhr = 1000072000,
        ExternalMemoryImageCreateInfoKhr = 1000072001,
        ExportMemoryAllocateInfoKhr = 1000072002,
        ImportMemoryWin32HandleInfoKhr = 1000073000,
        ExportMemoryWin32HandleInfoKhr = 1000073001,
        MemoryWin32HandlePropertiesKhr = 1000073002,
        MemoryGetWin32HandleInfoKhr = 1000073003,
        ImportMemoryFdInfoKhr = 1000074000,
        MemoryFdPropertiesKhr = 1000074001,
        MemoryGetFdInfoKhr = 1000074002,
        Win32KeyedMutexAcquireReleaseInfoKhr = 1000075000,
        PhysicalDeviceExternalSemaphoreInfoKhr = 1000076000,
        ExternalSemaphorePropertiesKhr = 1000076001,
        ExportSemaphoreCreateInfoKhr = 1000077000,
        ImportSemaphoreWin32HandleInfoKhr = 1000078000,
        ExportSemaphoreWin32HandleInfoKhr = 1000078001,
        D3D12FenceSubmitInfoKhr = 1000078002,
        SemaphoreGetWin32HandleInfoKhr = 1000078003,
        ImportSemaphoreFdInfoKhr = 1000079000,
        SemaphoreGetFdInfoKhr = 1000079001,
        PhysicalDevicePushDescriptorPropertiesKhr = 1000080000,
        PhysicalDevice16BitStorageFeaturesKhr = 1000083000,
        PresentRegionsKhr = 1000084000,
        DescriptorUpdateTemplateCreateInfoKhr = 1000085000,
        ObjectTableCreateInfoNvx = 1000086000,
        IndirectCommandsLayoutCreateInfoNvx = 1000086001,
        CmdProcessCommandsInfoNvx = 1000086002,
        CmdReserveSpaceForCommandsInfoNvx = 1000086003,
        DeviceGeneratedCommandsLimitsNvx = 1000086004,
        DeviceGeneratedCommandsFeaturesNvx = 1000086005,
        PipelineViewportWScalingStateCreateInfoNv = 1000087000,
        SurfaceCapabilities2Ext = 1000090000,
        DisplayPowerInfoExt = 1000091000,
        DeviceEventInfoExt = 1000091001,
        DisplayEventInfoExt = 1000091002,
        SwapchainCounterCreateInfoExt = 1000091003,
        PresentTimesInfoGoogle = 1000092000,
        PhysicalDeviceMultiviewPerViewAttributesPropertiesNvx = 1000097000,
        PipelineViewportSwizzleStateCreateInfoNv = 1000098000,
        PhysicalDeviceDiscardRectanglePropertiesExt = 1000099000,
        PipelineDiscardRectangleStateCreateInfoExt = 1000099001,
        PhysicalDeviceConservativeRasterizationPropertiesExt = 1000101000,
        PipelineRasterizationConservativeStateCreateInfoExt = 1000101001,
        HdrMetadataExt = 1000105000,
        SharedPresentSurfaceCapabilitiesKhr = 1000111000,
        PhysicalDeviceExternalFenceInfoKhr = 1000112000,
        ExternalFencePropertiesKhr = 1000112001,
        ExportFenceCreateInfoKhr = 1000113000,
        ImportFenceWin32HandleInfoKhr = 1000114000,
        ExportFenceWin32HandleInfoKhr = 1000114001,
        FenceGetWin32HandleInfoKhr = 1000114002,
        ImportFenceFdInfoKhr = 1000115000,
        FenceGetFdInfoKhr = 1000115001,
        PhysicalDevicePointClippingPropertiesKhr = 1000117000,
        RenderPassInputAttachmentAspectCreateInfoKhr = 1000117001,
        ImageViewUsageCreateInfoKhr = 1000117002,
        PipelineTessellationDomainOriginStateCreateInfoKhr = 1000117003,
        PhysicalDeviceSurfaceInfo2Khr = 1000119000,
        SurfaceCapabilities2Khr = 1000119001,
        SurfaceFormat2Khr = 1000119002,
        PhysicalDeviceVariablePointerFeaturesKhr = 1000120000,
        IOSSurfaceCreateInfoMvk = 1000122000,
        MacOSSurfaceCreateInfoMvk = 1000123000,
        MemoryDedicatedRequirementsKhr = 1000127000,
        MemoryDedicatedAllocateInfoKhr = 1000127001,
        PhysicalDeviceSamplerFilterMinmaxPropertiesExt = 1000130000,
        SamplerReductionModeCreateInfoExt = 1000130001,
        SampleLocationsInfoExt = 1000143000,
        RenderPassSampleLocationsBeginInfoExt = 1000143001,
        PipelineSampleLocationsStateCreateInfoExt = 1000143002,
        PhysicalDeviceSampleLocationsPropertiesExt = 1000143003,
        MultisamplePropertiesExt = 1000143004,
        BufferMemoryRequirementsInfo2Khr = 1000146000,
        ImageMemoryRequirementsInfo2Khr = 1000146001,
        ImageSparseMemoryRequirementsInfo2Khr = 1000146002,
        MemoryRequirements2Khr = 1000146003,
        SparseImageMemoryRequirements2Khr = 1000146004,
        ImageFormatListCreateInfoKhr = 1000147000,
        PhysicalDeviceBlendOperationAdvancedFeaturesExt = 1000148000,
        PhysicalDeviceBlendOperationAdvancedPropertiesExt = 1000148001,
        PipelineColorBlendAdvancedStateCreateInfoExt = 1000148002,
        PipelineCoverageToColorStateCreateInfoNv = 1000149000,
        PipelineCoverageModulationStateCreateInfoNv = 1000152000,
        SamplerYcbcrConversionCreateInfoKhr = 1000156000,
        SamplerYcbcrConversionInfoKhr = 1000156001,
        BindImagePlaneMemoryInfoKhr = 1000156002,
        ImagePlaneMemoryRequirementsInfoKhr = 1000156003,
        PhysicalDeviceSamplerYcbcrConversionFeaturesKhr = 1000156004,
        SamplerYcbcrConversionImageFormatPropertiesKhr = 1000156005,
        BindBufferMemoryInfoKhr = 1000157000,
        BindImageMemoryInfoKhr = 1000157001,
        ValidationCacheCreateInfoExt = 1000160000,
        ShaderModuleValidationCacheCreateInfoExt = 1000160001,
        DeviceQueueGlobalPriorityCreateInfoExt = 1000174000,
        ImportMemoryHostPointerInfoExt = 1000178000,
        MemoryHostPointerPropertiesExt = 1000178001,
        PhysicalDeviceExternalMemoryHostPropertiesExt = 1000178002,
    }

    public enum VkSystemAllocationScope : int {
        SystemAllocationScopeCommand = 0,
        SystemAllocationScopeObject = 1,
        SystemAllocationScopeCache = 2,
        SystemAllocationScopeDevice = 3,
        SystemAllocationScopeInstance = 4,
    }

    public enum VkInternalAllocationType : int {
        InternalAllocationTypeExecutable = 0,
    }

    public enum VkSamplerAddressMode : int {
        SamplerAddressModeRepeat = 0,
        SamplerAddressModeMirroredRepeat = 1,
        SamplerAddressModeClampToEdge = 2,
        SamplerAddressModeClampToBorder = 3,
        SamplerAddressModeMirrorClampToEdge = 4,
    }

    public enum VkFilter : int {
        FilterNearest = 0,
        FilterLinear = 1,
        FilterCubicImg = 1000015000,
    }

    public enum VkSamplerMipmapMode : int {
        SamplerMipmapModeNearest = 0,
        SamplerMipmapModeLinear = 1,
    }

    public enum VkVertexInputRate : int {
        VertexInputRateVertex = 0,
        VertexInputRateInstance = 1,
    }

    [Flags]
    public enum VkPipelineStageFlags : int {
        PipelineStageTopOfPipe = 0x1,
        PipelineStageDrawIndirect = 0x2,
        PipelineStageVertexInput = 0x4,
        PipelineStageVertexShader = 0x8,
        PipelineStageTessellationControlShader = 0x10,
        PipelineStageTessellationEvaluationShader = 0x20,
        PipelineStageGeometryShader = 0x40,
        PipelineStageFragmentShader = 0x80,
        PipelineStageEarlyFragmentTests = 0x100,
        PipelineStageLateFragmentTests = 0x200,
        PipelineStageColorAttachmentOutput = 0x400,
        PipelineStageComputeShader = 0x800,
        PipelineStageTransfer = 0x1000,
        PipelineStageBottomOfPipe = 0x2000,
        PipelineStageHost = 0x4000,
        PipelineStageAllGraphics = 0x8000,
        PipelineStageAllCommands = 0x10000,
        PipelineStageCommandProcessNvx = 0x20000,
    }

    [Flags]
    public enum VkSparseImageFormatFlags : int {
        SparseImageFormatSingleMiptail = 0x1,
        SparseImageFormatAlignedMipSize = 0x2,
        SparseImageFormatNonstandardBlockSize = 0x4,
    }

    [Flags]
    public enum VkSampleCountFlags : int {
        SampleCount1 = 0x1,
        SampleCount2 = 0x2,
        SampleCount4 = 0x4,
        SampleCount8 = 0x8,
        SampleCount16 = 0x10,
        SampleCount32 = 0x20,
        SampleCount64 = 0x40,
    }

    [Flags]
    public enum VkAttachmentDescriptionFlags : int {
        AttachmentDescriptionMayAlias = 0x1,
    }

    [Flags]
    public enum VkDescriptorPoolCreateFlags : int {
        DescriptorPoolCreateFreeDescriptorSet = 0x1,
    }

    [Flags]
    public enum VkDependencyFlags : int {
        DependencyByRegion = 0x1,
        DependencyViewLocalKhx = 0x2,
        DependencyDeviceGroupKhx = 0x4,
    }

    public enum VkObjectType : int {
        ObjectTypeUnknown = 0,
        ObjectTypeInstance = 1,
        ObjectTypePhysicalDevice = 2,
        ObjectTypeDevice = 3,
        ObjectTypeQueue = 4,
        ObjectTypeSemaphore = 5,
        ObjectTypeCommandBuffer = 6,
        ObjectTypeFence = 7,
        ObjectTypeDeviceMemory = 8,
        ObjectTypeBuffer = 9,
        ObjectTypeImage = 10,
        ObjectTypeEvent = 11,
        ObjectTypeQueryPool = 12,
        ObjectTypeBufferView = 13,
        ObjectTypeImageView = 14,
        ObjectTypeShaderModule = 15,
        ObjectTypePipelineCache = 16,
        ObjectTypePipelineLayout = 17,
        ObjectTypeRenderPass = 18,
        ObjectTypePipeline = 19,
        ObjectTypeDescriptorSetLayout = 20,
        ObjectTypeSampler = 21,
        ObjectTypeDescriptorPool = 22,
        ObjectTypeDescriptorSet = 23,
        ObjectTypeFramebuffer = 24,
        ObjectTypeCommandPool = 25,
        ObjectTypeSurfaceKhr = 1000000000,
        ObjectTypeSwapchainKhr = 1000001000,
        ObjectTypeDisplayKhr = 1000002000,
        ObjectTypeDisplayModeKhr = 1000002001,
        ObjectTypeDebugReportCallbackExt = 1000011000,
        ObjectTypeDescriptorUpdateTemplateKhr = 1000085000,
        ObjectTypeObjectTableNvx = 1000086000,
        ObjectTypeIndirectCommandsLayoutNvx = 1000086001,
        ObjectTypeSamplerYcbcrConversionKhr = 1000156000,
        ObjectTypeValidationCacheExt = 1000160000,
    }

    [Flags]
    public enum VkIndirectCommandsLayoutUsageFlagsNvx : int {
        IndirectCommandsLayoutUsageUnorderedSequences = 0x1,
        IndirectCommandsLayoutUsageSparseSequences = 0x2,
        IndirectCommandsLayoutUsageEmptyExecutions = 0x4,
        IndirectCommandsLayoutUsageIndexedSequences = 0x8,
    }

    public enum VkIndirectCommandsTokenTypeNvx : int {
        IndirectCommandsTokenTypePipeline = 0,
        IndirectCommandsTokenTypeDescriptorSet = 1,
        IndirectCommandsTokenTypeIndexBuffer = 2,
        IndirectCommandsTokenTypeVertexBuffer = 3,
        IndirectCommandsTokenTypePushConstant = 4,
        IndirectCommandsTokenTypeDrawIndexed = 5,
        IndirectCommandsTokenTypeDraw = 6,
        IndirectCommandsTokenTypeDispatch = 7,
    }

    [Flags]
    public enum VkObjectEntryUsageFlagsNvx : int {
        ObjectEntryUsageGraphics = 0x1,
        ObjectEntryUsageCompute = 0x2,
    }

    public enum VkObjectEntryTypeNvx : int {
        ObjectEntryTypeDescriptorSet = 0,
        ObjectEntryTypePipeline = 1,
        ObjectEntryTypeIndexBuffer = 2,
        ObjectEntryTypeVertexBuffer = 3,
        ObjectEntryTypePushConstant = 4,
    }

    public enum VkDescriptorUpdateTemplateTypeKhr : int {
        DescriptorUpdateTemplateTypeDescriptorSet = 0,
        DescriptorUpdateTemplateTypePushDescriptors = 1,
    }

    public enum VkViewportCoordinateSwizzleNv : int {
        ViewportCoordinateSwizzlePositiveX = 0,
        ViewportCoordinateSwizzleNegativeX = 1,
        ViewportCoordinateSwizzlePositiveY = 2,
        ViewportCoordinateSwizzleNegativeY = 3,
        ViewportCoordinateSwizzlePositiveZ = 4,
        ViewportCoordinateSwizzleNegativeZ = 5,
        ViewportCoordinateSwizzlePositiveW = 6,
        ViewportCoordinateSwizzleNegativeW = 7,
    }

    public enum VkDiscardRectangleModeExt : int {
        DiscardRectangleModeInclusive = 0,
        DiscardRectangleModeExclusive = 1,
    }

    [Flags]
    public enum VkSubpassDescriptionFlags : int {
        SubpassDescriptionPerViewAttributesNvx = 0x1,
        SubpassDescriptionPerViewPositionXOnlyNvx = 0x2,
    }

    public enum VkPointClippingBehaviorKhr : int {
        PointClippingBehaviorAllClipPlanes = 0,
        PointClippingBehaviorUserClipPlanesOnly = 1,
    }

    public enum VkCoverageModulationModeNv : int {
        CoverageModulationModeNone = 0,
        CoverageModulationModeRgb = 1,
        CoverageModulationModeAlpha = 2,
        CoverageModulationModeRgba = 3,
    }

    public enum VkValidationCacheHeaderVersionExt : int {
        ValidationCacheHeaderVersionOne = 1,
    }

    public enum VkShaderInfoTypeAmd : int {
        ShaderInfoTypeStatistics = 0,
        ShaderInfoTypeBinary = 1,
        ShaderInfoTypeDisassembly = 2,
    }

    public enum VkQueueGlobalPriorityExt : int {
        QueueGlobalPriorityLow = 128,
        QueueGlobalPriorityMedium = 256,
        QueueGlobalPriorityHigh = 512,
        QueueGlobalPriorityRealtime = 1024,
    }

    public enum VkConservativeRasterizationModeExt : int {
        Disabled = 0,
        Overestimate = 1,
        Underestimate = 2,
    }

    public enum VkColorSpaceKhr : int {
        SrgbNonlinear = 0,
        DisplayP3NonlinearExt = 1000104001,
        ExtendedSrgbLinearExt = 1000104002,
        DciP3LinearExt = 1000104003,
        DciP3NonlinearExt = 1000104004,
        Bt709LinearExt = 1000104005,
        Bt709NonlinearExt = 1000104006,
        Bt2020LinearExt = 1000104007,
        Hdr10St2084Ext = 1000104008,
        DolbyvisionExt = 1000104009,
        Hdr10HlgExt = 1000104010,
        AdobergbLinearExt = 1000104011,
        AdobergbNonlinearExt = 1000104012,
        ColorSpacePassThroughExt = 1000104013,
        ColorSpaceExtendedSrgbNonlinearExt = 1000104014,
    }

    [Flags]
    public enum VkCompositeAlphaFlagsKhr : int {
        Opaque = 0x1,
        PreMultiplied = 0x2,
        PostMultiplied = 0x4,
        Inherit = 0x8,
    }

    [Flags]
    public enum VkDisplayPlaneAlphaFlagsKhr : int {
        Opaque = 0x1,
        Global = 0x2,
        PerPixel = 0x4,
        PerPixelPremultiplied = 0x8,
    }

    public enum VkPresentModeKhr : int {
        Immediate = 0,
        Mailbox = 1,
        Fifo = 2,
        FifoRelaxed = 3,
        SharedDemandRefresh = 1000111000,
        SharedContinuousRefresh = 1000111001,
    }

    [Flags]
    public enum VkSurfaceTransformFlagsKhr : int {
        Identity = 0x1,
        Rotate90 = 0x2,
        Rotate180 = 0x4,
        Rotate270 = 0x8,
        HorizontalMirror = 0x10,
        HorizontalMirrorRotate90 = 0x20,
        HorizontalMirrorRotate180 = 0x40,
        HorizontalMirrorRotate270 = 0x80,
        Inherit = 0x100,
    }

    [Flags]
    public enum VkDebugReportFlagsExt : int {
        Information = 0x1,
        Warning = 0x2,
        PerformanceWarning = 0x4,
        Error = 0x8,
        Debug = 0x10,
    }

    public enum VkDebugReportObjectTypeExt : int {
        DebugReportObjectTypeUnknown = 0,
        DebugReportObjectTypeInstance = 1,
        DebugReportObjectTypePhysicalDevice = 2,
        DebugReportObjectTypeDevice = 3,
        DebugReportObjectTypeQueue = 4,
        DebugReportObjectTypeSemaphore = 5,
        DebugReportObjectTypeCommandBuffer = 6,
        DebugReportObjectTypeFence = 7,
        DebugReportObjectTypeDeviceMemory = 8,
        DebugReportObjectTypeBuffer = 9,
        DebugReportObjectTypeImage = 10,
        DebugReportObjectTypeEvent = 11,
        DebugReportObjectTypeQueryPool = 12,
        DebugReportObjectTypeBufferView = 13,
        DebugReportObjectTypeImageView = 14,
        DebugReportObjectTypeShaderModule = 15,
        DebugReportObjectTypePipelineCache = 16,
        DebugReportObjectTypePipelineLayout = 17,
        DebugReportObjectTypeRenderPass = 18,
        DebugReportObjectTypePipeline = 19,
        DebugReportObjectTypeDescriptorSetLayout = 20,
        DebugReportObjectTypeSampler = 21,
        DebugReportObjectTypeDescriptorPool = 22,
        DebugReportObjectTypeDescriptorSet = 23,
        DebugReportObjectTypeFramebuffer = 24,
        DebugReportObjectTypeCommandPool = 25,
        DebugReportObjectTypeSurfaceKhr = 26,
        DebugReportObjectTypeSwapchainKhr = 27,
        DebugReportObjectTypeDebugReportCallbackExt = 28,
        DebugReportObjectTypeDisplayKhr = 29,
        DebugReportObjectTypeDisplayModeKhr = 30,
        DebugReportObjectTypeObjectTableNvx = 31,
        DebugReportObjectTypeIndirectCommandsLayoutNvx = 32,
        DebugReportObjectTypeValidationCacheExt = 33,
        DebugReportObjectTypeDescriptorUpdateTemplateKhr = 1000085000,
        DebugReportObjectTypeSamplerYcbcrConversionKhr = 1000156000,
    }

    public enum VkRasterizationOrderAmd : int {
        RasterizationOrderStrict = 0,
        RasterizationOrderRelaxed = 1,
    }

    [Flags]
    public enum VkExternalMemoryHandleTypeFlagsNv : int {
        ExternalMemoryHandleTypeOpaqueWin32 = 0x1,
        ExternalMemoryHandleTypeOpaqueWin32Kmt = 0x2,
        ExternalMemoryHandleTypeD3D11Image = 0x4,
        ExternalMemoryHandleTypeD3D11ImageKmt = 0x8,
    }

    [Flags]
    public enum VkExternalMemoryFeatureFlagsNv : int {
        ExternalMemoryFeatureDedicatedOnly = 0x1,
        ExternalMemoryFeatureExportable = 0x2,
        ExternalMemoryFeatureImportable = 0x4,
    }

    public enum VkValidationCheckExt : int {
        ValidationCheckAll = 0,
        ValidationCheckShaders = 1,
    }

    [Flags]
    public enum VkExternalMemoryHandleTypeFlagsKhr : int {
        ExternalMemoryHandleTypeOpaqueFd = 0x1,
        ExternalMemoryHandleTypeOpaqueWin32 = 0x2,
        ExternalMemoryHandleTypeOpaqueWin32Kmt = 0x4,
        ExternalMemoryHandleTypeD3D11Texture = 0x8,
        ExternalMemoryHandleTypeD3D11TextureKmt = 0x10,
        ExternalMemoryHandleTypeD3D12Heap = 0x20,
        ExternalMemoryHandleTypeD3D12Resource = 0x40,
        ExternalMemoryHandleTypeDmaBufBitExt = 0x200,
        ExternalMemoryHandleTypeHostAllocationBitExt = 0x80,
        ExternalMemoryHandleTypeHostMappedForeignMemoryBitExt = 0x100,
    }

    [Flags]
    public enum VkExternalMemoryFeatureFlagsKhr : int {
        ExternalMemoryFeatureDedicatedOnly = 0x1,
        ExternalMemoryFeatureExportable = 0x2,
        ExternalMemoryFeatureImportable = 0x4,
    }

    [Flags]
    public enum VkExternalSemaphoreHandleTypeFlagsKhr : int {
        ExternalSemaphoreHandleTypeOpaqueFd = 0x1,
        ExternalSemaphoreHandleTypeOpaqueWin32 = 0x2,
        ExternalSemaphoreHandleTypeOpaqueWin32Kmt = 0x4,
        ExternalSemaphoreHandleTypeD3D12Fence = 0x8,
        ExternalSemaphoreHandleTypeSyncFd = 0x10,
    }

    [Flags]
    public enum VkExternalSemaphoreFeatureFlagsKhr : int {
        ExternalSemaphoreFeatureExportable = 0x1,
        ExternalSemaphoreFeatureImportable = 0x2,
    }

    [Flags]
    public enum VkSemaphoreImportFlagsKhr : int {
        SemaphoreImportTemporary = 0x1,
    }

    [Flags]
    public enum VkExternalFenceHandleTypeFlagsKhr : int {
        ExternalFenceHandleTypeOpaqueFd = 0x1,
        ExternalFenceHandleTypeOpaqueWin32 = 0x2,
        ExternalFenceHandleTypeOpaqueWin32Kmt = 0x4,
        ExternalFenceHandleTypeSyncFd = 0x8,
    }

    [Flags]
    public enum VkExternalFenceFeatureFlagsKhr : int {
        ExternalFenceFeatureExportable = 0x1,
        ExternalFenceFeatureImportable = 0x2,
    }

    [Flags]
    public enum VkFenceImportFlagsKhr : int {
        FenceImportTemporary = 0x1,
    }

    [Flags]
    public enum VkSurfaceCounterFlagsExt : int {
        SurfaceCounterVblankExt = 0x1,
    }

    public enum VkDisplayPowerStateExt : int {
        DisplayPowerStateOff = 0,
        DisplayPowerStateSuspend = 1,
        DisplayPowerStateOn = 2,
    }

    public enum VkDeviceEventTypeExt : int {
        DeviceEventTypeDisplayHotplug = 0,
    }

    public enum VkDisplayEventTypeExt : int {
        DisplayEventTypeFirstPixelOut = 0,
    }

    [Flags]
    public enum VkPeerMemoryFeatureFlagsKhx : int {
        PeerMemoryFeatureCopySrc = 0x1,
        PeerMemoryFeatureCopyDst = 0x2,
        PeerMemoryFeatureGenericSrc = 0x4,
        PeerMemoryFeatureGenericDst = 0x8,
    }

    [Flags]
    public enum VkMemoryAllocateFlagsKhx : int {
        MemoryAllocateDeviceMask = 0x1,
    }

    [Flags]
    public enum VkDeviceGroupPresentModeFlagsKhx : int {
        DeviceGroupPresentModeLocal = 0x1,
        DeviceGroupPresentModeRemote = 0x2,
        DeviceGroupPresentModeSum = 0x4,
        DeviceGroupPresentModeLocalMultiDevice = 0x8,
    }

    [Flags]
    public enum VkSwapchainCreateFlagsKhr : int {
        SwapchainCreateBindSfrBitKhx = 0x1,
    }

    public enum VkTessellationDomainOriginKhr : int {
        TessellationDomainOriginUpperLeft = 0,
        TessellationDomainOriginLowerLeft = 1,
    }

    public enum VkSamplerYcbcrModelConversionKhr : int {
        SamplerYcbcrModelConversionRgbIdentity = 0,
        SamplerYcbcrModelConversionYcbcrIdentity = 1,
        SamplerYcbcrModelConversionYcbcr709 = 2,
        SamplerYcbcrModelConversionYcbcr601 = 3,
        SamplerYcbcrModelConversionYcbcr2020 = 4,
    }

    public enum VkSamplerYcbcrRangeKhr : int {
        SamplerYcbcrRangeItuFull = 0,
        SamplerYcbcrRangeItuNarrow = 1,
    }

    public enum VkChromaLocationKhr : int {
        ChromaLocationCositedEven = 0,
        ChromaLocationMidpoint = 1,
    }

    public enum VkSamplerReductionModeExt : int {
        SamplerReductionModeWeightedAverage = 0,
        SamplerReductionModeMin = 1,
        SamplerReductionModeMax = 2,
    }

    public enum VkBlendOverlapExt : int {
        BlendOverlapUncorrelated = 0,
        BlendOverlapDisjoint = 1,
        BlendOverlapConjoint = 2,
    }
}
